### ISSUE TITLE
Testing Post, Get, Put

### ISSUE THREAD

**Issue by alokprakash731** [food-boot/food_delivery_web_app_backend_springboot#38]
1. Run the project, swagger is ready : http://localhost:8080/food-boot/swagger-ui.html
2. Go to user-controller, POST method, try executing from swagger it generates Request url: https://localhost:8080/food-boot/users
3. Issue is https didn't works and we server response as undocumented with TypeError: Failed to fetch
4. Use http in post man (remove s from https) , it works fine.(http://localhost:8080/food-boot/users)
5. Now i got the response from postman as:
   

```
<UserRest>
    <userId>oQHosjyA82z1CRXVfIO93ysW2dkuI9</userId>
    <email>prakashji@gmail.com</email>
    <firstName>prakash</firstName>
    <lastName>ji</lastName>
    <picURL/>
    <userType>user</userType>
</UserRest>
```

6. Now i want to get the user created above using GET method, swagger any how will not work for execution  because it creates https request url, so i gone to postman there but i have doubt what should i fill for authorization and token because there is no steps mentioned in Read Me file and i was new for security project but some how i thought and tried to fill like below:
get url: http://localhost:8080/food-boot/users
Under Headers i guessed and put key value as authorization and Value as Bearer and Token secret value:
Key : authorization    
Value: Bearer Jsaf9GHasdf732rvas

7. So, please guide or give proper steps in read me file for testing GET , PUT wherever authentication needed. I am new to security tokens and all just wanted to clear the concepts and if you have extra time then please correct the Swagger implementation to so that all execute works fine with http method.

**Comment by shehand** [comment]
In swagger, you can select whether it is HTTP or https. Try to switch HTTP in swagger and then executing the requests.

**Comment by shehand** [comment]
Seems like this issue is no longer valid.
